#!/usr/bin/env bash

#-----------------------------------------
# Homebrew
#-----------------------------------------

alias dir-brew='cd /usr/local/Cellar'

export HOMEBREW_CASK_OPTS="--appdir=/Applications"
