#!/bin/sh

alias repo-amend='git commit -a --amend'
alias repo-ca='git commit -a'
alias repo-co='git checkout'
alias repo-history='git log --oneline --abbrev-commit --all --graph --decorate --color'
alias repo-po='git push origin'
alias repo-pu='git push upstream'
alias repo-undo='git reset HEAD~1 --mixed'
alias repo-up='git pull --rebase --prune'