#!/bin/sh

apm install atom-material-ui
apm install build
apm install build-npm-apm
apm install devdocs
apm install editorconfig
apm install file-icons
apm install git-blame
apm install git-control
apm install git-history
apm install git-log
apm install highlight-selected
apm install hyperclick
apm install js-hyperclick
apm install language-babel
apm install linter
apm install linter-eslint
apm install linter-php
apm install linter-sass-lint
apm install merge-conflicts
apm install minimap
apm install oceanic-next
apm install pigments
apm install project-manager
apm install react
apm install split-diff
apm install terminal-plus
apm install toggle-quotes
